# --- GENERAL SETTINGS ---
# Don't print a new line at the beginning of the prompt
add_newline = false

# --- CHARACTER ---
# The symbol shown at the start of the prompt
[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"

# --- GIT ---
# Display current git branch
[git_branch]
symbol = " "
style = "bold purple"

# --- DIRECTORY ---
# Current working directory configuration
[directory]
truncation_length = 3
style = "bold cyan"

# --- COMMAND DURATION ---
# Show how long a command took to execute
[cmd_duration]
min_time = 2000  # Show only if it takes more than 2 seconds (in milliseconds)
format = "took [$duration]($style) "
style = "yellow bold"
